- name: example - gather_facts
  hosts: web
  gather_facts: yes

  tasks:
  - debug:
      msg: "{{ ansible_facts }}"

  - debug:
      msg: "{{ ansible_facts.os_family }}"

  - debug:
      var: ansible_facts.os_family
