- name: example - register
  hosts: all

  tasks:
  - name: check hostname
    command: hostname
    register: result

  - name: print result
    debug:
      var: result

  - name: print hostname
    debug:
      var: result.stdout